#!/usr/bin/env python3
"""
File: test_kmc.py
Author: Joshua Holmes
Email: jbh92@case.edu

Containts tests for the funcitons in the kcm.py module.
"""

# Imports
import pytest
import numpy as np
import numpy.testing as nptest

import myo5space.kmc as kmc


def test_kmc_transmat():
    """
    Test that the trun_transmat function returns the correct 2D matrix of
    shape (9,9).
    """
    # Setup
    kd1 = 1.
    kd2 = 2.
    kh = 3.
    kps = 4.
    kfpp = 5.
    kfpm = 6.
    b = 0.5
    # Excercise
    got = kmc.kmc_transmat(kd1, kd2, kh, kps, kfpp, kfpm, b)
    # Verify
    exp = np.array([[-3. ,  0. ,  0. ,  0. ,  0. ,  4. ,  2.5,  0. ,  0. ],
                    [ 1. , -4. ,  0. ,  0. ,  0. ,  0. ,  0. ,  0. ,  0. ],
                    [ 0. ,  3. , -9. ,  0. ,  0. ,  0. ,  0. ,  0. ,  0. ],
                    [ 0. ,  0. ,  5. , -4. ,  0. ,  0. ,  0. ,  0. ,  0. ],
                    [ 0. ,  0. ,  0. ,  4. , -0. ,  0. ,  0. ,  0. ,  0. ],
                    [ 0. ,  0. ,  3. ,  0. ,  0. , -4. ,  0. ,  0. ,  0. ],
                    [ 2. ,  0. ,  0. ,  0. ,  0. ,  0. , -9.5,  0. ,  0. ],
                    [ 0. ,  0. ,  0. ,  0. ,  0. ,  0. ,  6. , -0. ,  0. ],
                    [ 0. ,  1. ,  1. ,  0. ,  0. ,  0. ,  1. ,  0. , -0. ]])

    assert got.shape == (9, 9)
    nptest.assert_allclose(exp, got)


def test_update_kmc_transmat():
    """
    Test that the update_transmat function returns the correct 2D matrix with
    shape (9,9). The starting transmat is that similar to what would be
    generated by the init_transmat function if given negative const_force and
    kfp arguments, resulting in a matrix that would need to be updated during
    the simulation.
    """
    # Setup
    transmat = np.array([[-3.   ,  0.   ,  0.   ,  0.   ,  0.   ,  4.   , -0.5,  0.   , 0.   ],
                         [ 1.   , -4.   ,  0.   ,  0.   ,  0.   ,  0.   ,  0.   ,  0.   , 0.   ],
                         [ 0.   ,  3.   ,  0.5,  0.   ,  0.   ,  0.   ,  0.   ,  0.   , 0.   ],
                         [ 0.   ,  0.   , -1.   , -4.   ,  0.   ,  0.   ,  0.   ,  0.   , 0.   ],
                         [ 0.   ,  0.   ,  0.   ,  4.   , -0.   ,  0.   ,  0.   ,  0.   , 0.   ],
                         [ 0.   ,  0.   , -0.5,  0.   ,  0.   , -4.   ,  0.   ,  0.   , 0.   ],
                         [ 2.   ,  0.   ,  0.   ,  0.   ,  0.   ,  0.   ,  0.5,  0.   , 0.   ],
                         [ 0.   ,  0.   ,  0.   ,  0.   ,  0.   ,  0.   , -1.   , -0.   , 0.   ],
                         [ 0.   ,  1.   ,  1.   ,  0.   ,  0.   ,  0.   ,  1.   ,  0.   , -0.   ]])
    kd1 = 1.
    kfpp = 7.
    kfpm = 8.
    b = 0.5
    # Excercise
    # Funciton updates transmat in place.
    kmc.update_transmat(transmat, kfpp, kfpm, b, kd1)
    # Validate
    exp = np.array([[-3. ,  0. ,  0. ,  0. ,  0. ,  4. ,  3.5,  0. ,  0. ],
                    [ 1. , -4. ,  0. ,  0. ,  0. ,  0. ,  0. ,  0. ,  0. ],
                    [ 0. ,  3. , -12. ,  0. ,  0. ,  0. ,  0. ,  0. ,  0. ],
                    [ 0. ,  0. ,  7. , -4. ,  0. ,  0. ,  0. ,  0. ,  0. ],
                    [ 0. ,  0. ,  0. ,  4. , -0. ,  0. ,  0. ,  0. ,  0. ],
                    [ 0. ,  0. ,  4. ,  0. ,  0. , -4. ,  0. ,  0. ,  0. ],
                    [ 2. ,  0. ,  0. ,  0. ,  0. ,  0. , -12.5,  0. ,  0. ],
                    [ 0. ,  0. ,  0. ,  0. ,  0. ,  0. ,  8. , -0. ,  0. ],
                    [ 0. ,  1. ,  1. ,  0. ,  0. ,  0. ,  1. ,  0. , -0. ]])
    nptest.assert_allclose(exp, transmat)


def test_init_transmat_constforce():
    """
    Test that the init_transmat function returns the correct matrix when given
    a constant force argument and negative kfp arguments.
    """
    # Setup
    const_force = 1.
    kfpp = -1.
    kfpm = -1.

    kd1 = 1.
    kd2 = 2.
    kh = 3.
    kps = 4.
    Delta = 36.
    beta = 0.24552442427253968
    L = 35.
    l_p = 310.
    nu_c = 184.
    theta_c = np.pi/3
    theta_F = 0.
    b = 0.065
    a = 1.0
    D_h = 57000000.0
    # Excercise
    got = kmc.init_transmat(const_force,
                            kfpp,
                            kfpm,
                            kd1,
                            kd2,
                            kh,
                            kps,
                            b,
                            Delta,
                            L,
                            l_p,
                            beta,
                            nu_c,
                            theta_c,
                            theta_F,
                            a,
                            D_h)
    # Validate
    exp = np.array([[  -3.        ,    0.        ,    0.        ,    0.        , 0.        ,    4.        ,   36.90484031,    0.        , 0.        ],
                    [   1.        ,   -4.        ,    0.        ,    0.        , 0.        ,    0.        ,    0.        ,    0.        , 0.        ],
                    [   0.        ,    3.        , -570.40216894,    0.        , 0.        ,    0.        ,    0.        ,    0.        , 0.        ],
                    [   0.        ,    0.        ,  567.76677397,   -4.        , 0.        ,    0.        ,    0.        ,    0.        , 0.        ],
                    [   0.        ,    0.        ,    0.        ,    4.        , -0.        ,    0.        ,    0.        ,    0.        , 0.        ],
                    [   0.        ,    0.        ,    1.63539497,    0.        , 0.        ,   -4.        ,    0.        ,    0.        , 0.        ],
                    [   2.        ,    0.        ,    0.        ,    0.        , 0.        ,    0.        ,  -63.06476294,    0.        , 0.        ],
                    [   0.        ,    0.        ,    0.        ,    0.        , 0.        ,    0.        ,   25.15992264,   -0.        , 0.        ],
                    [   0.        ,    1.        ,    1.        ,    0.        , 0.        ,    0.        ,    1.        ,    0.        , -0.        ]])
    nptest.assert_allclose(exp, got)


def test_init_transmat_zeroforce():
    """
    Test that the init_transmat function returns the correct matrix when given
    a zero-valued constant force argument and negative kfp arguments.
    """
    # Setup
    const_force = 0.
    kfpp = -1.
    kfpm = -1.

    kd1 = 1.
    kd2 = 2.
    kh = 3.
    kps = 4.
    Delta = 36.
    beta = 0.24552442427253968
    L = 35.
    l_p = 310.
    nu_c = 184.
    theta_c = np.pi/3
    theta_F = 0.
    b = 0.065
    a = 1.0
    D_h = 57000000.0
    # Excercise
    got = kmc.init_transmat(const_force,
                            kfpp,
                            kfpm,
                            kd1,
                            kd2,
                            kh,
                            kps,
                            b,
                            Delta,
                            L,
                            l_p,
                            beta,
                            nu_c,
                            theta_c,
                            theta_F,
                            a,
                            D_h)
    # Validate
    exp = np.array([[-3.00000000e+00,  0.00000000e+00,  0.00000000e+00, 0.00000000e+00,  0.00000000e+00,  4.00000000e+00, 1.94943390e+02,  0.00000000e+00,  0.00000000e+00],
                    [ 1.00000000e+00, -4.00000000e+00,  0.00000000e+00, 0.00000000e+00,  0.00000000e+00,  0.00000000e+00, 0.00000000e+00,  0.00000000e+00,  0.00000000e+00],
                    [ 0.00000000e+00,  3.00000000e+00, -3.00013033e+03, 0.00000000e+00,  0.00000000e+00,  0.00000000e+00, 0.00000000e+00,  0.00000000e+00,  0.00000000e+00],
                    [ 0.00000000e+00,  0.00000000e+00,  2.99912908e+03, -4.00000000e+00,  0.00000000e+00,  0.00000000e+00, 0.00000000e+00,  0.00000000e+00,  0.00000000e+00],
                    [ 0.00000000e+00,  0.00000000e+00,  0.00000000e+00, 4.00000000e+00, -0.00000000e+00,  0.00000000e+00, 0.00000000e+00,  0.00000000e+00,  0.00000000e+00],
                    [ 0.00000000e+00,  0.00000000e+00,  1.25248158e-03, 0.00000000e+00,  0.00000000e+00, -4.00000000e+00, 0.00000000e+00,  0.00000000e+00,  0.00000000e+00],
                    [ 2.00000000e+00,  0.00000000e+00,  0.00000000e+00, 0.00000000e+00,  0.00000000e+00,  0.00000000e+00, -1.95962659e+02,  0.00000000e+00,  0.00000000e+00],
                    [ 0.00000000e+00,  0.00000000e+00,  0.00000000e+00, 0.00000000e+00,  0.00000000e+00,  0.00000000e+00, 1.92689473e-02, -0.00000000e+00,  0.00000000e+00],
                    [ 0.00000000e+00,  1.00000000e+00,  1.00000000e+00, 0.00000000e+00,  0.00000000e+00,  0.00000000e+00, 1.00000000e+00,  0.00000000e+00, -0.00000000e+00]])
    nptest.assert_allclose(exp, got)


def test_init_transmat_constkfp():
    """
    Test the init_transmat function for when given constant kfp arguments and
    negative const_force.
    """
    # Setup
    const_force = -1
    kfpp = 567.7667739735654
    kfpm = 25.15992263560264
    kd1 = 1.
    kd2 = 2.
    kh = 3.
    kps = 4.
    Delta = 36.
    beta = 0.24552442427253968
    L = 35.
    l_p = 310.
    nu_c = 184.
    theta_c = np.pi/3
    theta_F = 0.
    b = 0.065
    a = 1.0
    D_h = 57000000.0
    # Excercise
    got = kmc.init_transmat(const_force,
                            kfpp,
                            kfpm,
                            kd1,
                            kd2,
                            kh,
                            kps,
                            b,
                            Delta,
                            L,
                            l_p,
                            beta,
                            nu_c,
                            theta_c,
                            theta_F,
                            a,
                            D_h)
    # Validate
    exp = np.array([[  -3.        ,    0.        ,    0.        ,    0.        , 0.        ,    4.        ,   36.90484031,    0.        , 0.        ],
                    [   1.        ,   -4.        ,    0.        ,    0.        , 0.        ,    0.        ,    0.        ,    0.        , 0.        ],
                    [   0.        ,    3.        , -570.40216894,    0.        , 0.        ,    0.        ,    0.        ,    0.        , 0.        ],
                    [   0.        ,    0.        ,  567.76677397,   -4.        , 0.        ,    0.        ,    0.        ,    0.        , 0.        ],
                    [   0.        ,    0.        ,    0.        ,    4.        , -0.        ,    0.        ,    0.        ,    0.        , 0.        ],
                    [   0.        ,    0.        ,    1.63539497,    0.        , 0.        ,   -4.        ,    0.        ,    0.        , 0.        ],
                    [   2.        ,    0.        ,    0.        ,    0.        , 0.        ,    0.        ,  -63.06476294,    0.        , 0.        ],
                    [   0.        ,    0.        ,    0.        ,    0.        , 0.        ,    0.        ,   25.15992264,   -0.        , 0.        ],
                    [   0.        ,    1.        ,    1.        ,    0.        , 0.        ,    0.        ,    1.        ,    0.        , -0.        ]])
    nptest.assert_allclose(exp, got)




def test_init_transmat_onlyconstkfpp():
    """
    Test the init_transmat function for when given a positive kfpp argument but
    const_force and kfpp are negative. Should default to a matrix indicating the
    need to update kfpp and kfpm during the simulation.
    """
    # Setup
    const_force = -1.
    kfpp = 567.7667739735654
    kfpm = -1.

    kd1 = 1.
    kd2 = 2.
    kh = 3.
    kps = 4.
    Delta = 36.
    beta = 0.24552442427253968
    L = 35.
    l_p = 310.
    nu_c = 184.
    theta_c = np.pi/3
    theta_F = 0.
    b = 0.065
    a = 1.0
    D_h = 57000000.0
    # Excercise
    got = kmc.init_transmat(const_force,
                            kfpp,
                            kfpm,
                            kd1,
                            kd2,
                            kh,
                            kps,
                            b,
                            Delta,
                            L,
                            l_p,
                            beta,
                            nu_c,
                            theta_c,
                            theta_F,
                            a,
                            D_h)
    # Validate
    exp = np.array([[-3.   ,  0.   ,  0.   ,  0.   ,  0.   ,  4.   , -0.065,  0.   , 0.   ],
                    [ 1.   , -4.   ,  0.   ,  0.   ,  0.   ,  0.   ,  0.   ,  0.   , 0.   ],
                    [ 0.   ,  3.   ,  0.065,  0.   ,  0.   ,  0.   ,  0.   ,  0.   , 0.   ],
                    [ 0.   ,  0.   , -1.   , -4.   ,  0.   ,  0.   ,  0.   ,  0.   , 0.   ],
                    [ 0.   ,  0.   ,  0.   ,  4.   , -0.   ,  0.   ,  0.   ,  0.   , 0.   ],
                    [ 0.   ,  0.   , -0.065,  0.   ,  0.   , -4.   ,  0.   ,  0.   , 0.   ],
                    [ 2.   ,  0.   ,  0.   ,  0.   ,  0.   ,  0.   ,  0.065,  0.   , 0.   ],
                    [ 0.   ,  0.   ,  0.   ,  0.   ,  0.   ,  0.   , -1.   , -0.   , 0.   ],
                    [ 0.   ,  1.   ,  1.   ,  0.   ,  0.   ,  0.   ,  1.   ,  0.   , -0.   ]])
    nptest.assert_allclose(exp, got)



def test_init_transmat_onlyconstkfpm():
    """
    Test the init_transmat function for when given a positive kfpm argument but
    const_force and kfpm are negative. Should default to a matrix indicating the
    need to update kfpp and kfpm during the simulation.
    """
    # Setup
    const_force = -1.
    kfpp = -1.
    kfpm = 25.15992263560264

    kd1 = 1.
    kd2 = 2.
    kh = 3.
    kps = 4.
    Delta = 36.
    beta = 0.24552442427253968
    L = 35.
    l_p = 310.
    nu_c = 184.
    theta_c = np.pi/3
    theta_F = 0.
    b = 0.065
    a = 1.0
    D_h = 57000000.0
    # Excercise
    got = kmc.init_transmat(const_force,
                            kfpp,
                            kfpm,
                            kd1,
                            kd2,
                            kh,
                            kps,
                            b,
                            Delta,
                            L,
                            l_p,
                            beta,
                            nu_c,
                            theta_c,
                            theta_F,
                            a,
                            D_h)
    # Validate
    exp = np.array([[-3.   ,  0.   ,  0.   ,  0.   ,  0.   ,  4.   , -0.065,  0.   , 0.   ],
                    [ 1.   , -4.   ,  0.   ,  0.   ,  0.   ,  0.   ,  0.   ,  0.   , 0.   ],
                    [ 0.   ,  3.   ,  0.065,  0.   ,  0.   ,  0.   ,  0.   ,  0.   , 0.   ],
                    [ 0.   ,  0.   , -1.   , -4.   ,  0.   ,  0.   ,  0.   ,  0.   , 0.   ],
                    [ 0.   ,  0.   ,  0.   ,  4.   , -0.   ,  0.   ,  0.   ,  0.   , 0.   ],
                    [ 0.   ,  0.   , -0.065,  0.   ,  0.   , -4.   ,  0.   ,  0.   , 0.   ],
                    [ 2.   ,  0.   ,  0.   ,  0.   ,  0.   ,  0.   ,  0.065,  0.   , 0.   ],
                    [ 0.   ,  0.   ,  0.   ,  0.   ,  0.   ,  0.   , -1.   , -0.   , 0.   ],
                    [ 0.   ,  1.   ,  1.   ,  0.   ,  0.   ,  0.   ,  1.   ,  0.   , -0.   ]])
    nptest.assert_allclose(exp, got)


def test_init_transmat_allconst():
    """
    Test the init_transmat function for when given both constant const_force
    and kfp arguments. The resulting matrix should be one honoring the
    const_force argument.
    """
    # Setup
    const_force = 1.
    kfpp = 10000.
    kfpm = 5000.
    kd1 = 1.
    kd2 = 2.
    kh = 3.
    kps = 4.
    Delta = 36.
    beta = 0.24552442427253968
    L = 35.
    l_p = 310.
    nu_c = 184.
    theta_c = np.pi/3
    theta_F = 0.
    b = 0.065
    a = 1.0
    D_h = 57000000.0
    # Excercise
    got = kmc.init_transmat(const_force,
                            kfpp,
                            kfpm,
                            kd1,
                            kd2,
                            kh,
                            kps,
                            b,
                            Delta,
                            L,
                            l_p,
                            beta,
                            nu_c,
                            theta_c,
                            theta_F,
                            a,
                            D_h)
    # Validate
    exp = np.array([[  -3.        ,    0.        ,    0.        ,    0.        , 0.        ,    4.        ,   36.90484031,    0.        , 0.        ],
                    [   1.        ,   -4.        ,    0.        ,    0.        , 0.        ,    0.        ,    0.        ,    0.        , 0.        ],
                    [   0.        ,    3.        , -570.40216894,    0.        , 0.        ,    0.        ,    0.        ,    0.        , 0.        ],
                    [   0.        ,    0.        ,  567.76677397,   -4.        , 0.        ,    0.        ,    0.        ,    0.        , 0.        ],
                    [   0.        ,    0.        ,    0.        ,    4.        , -0.        ,    0.        ,    0.        ,    0.        , 0.        ],
                    [   0.        ,    0.        ,    1.63539497,    0.        , 0.        ,   -4.        ,    0.        ,    0.        , 0.        ],
                    [   2.        ,    0.        ,    0.        ,    0.        , 0.        ,    0.        ,  -63.06476294,    0.        , 0.        ],
                    [   0.        ,    0.        ,    0.        ,    0.        , 0.        ,    0.        ,   25.15992264,   -0.        , 0.        ],
                    [   0.        ,    1.        ,    1.        ,    0.        , 0.        ,    0.        ,    1.        ,    0.        , -0.        ]])
    nptest.assert_allclose(exp, got)


def test_init_transmat_varforce():
    """
    Test the init_transmat function for when const_force and kfp arguments are
    all negative. The resulting matrix should indicate the need to update kfpp
    and kfpm during the simulation.
    """
    # Setup
    const_force = -1.
    kfpp = -1.
    kfpm = -1.

    kd1 = 1.
    kd2 = 2.
    kh = 3.
    kps = 4.
    Delta = 36.
    beta = 0.24552442427253968
    L = 35.
    l_p = 310.
    nu_c = 184.
    theta_c = np.pi/3
    theta_F = 0.
    b = 0.065
    a = 1.0
    D_h = 57000000.0
    # Excercise
    got = kmc.init_transmat(const_force,
                            kfpp,
                            kfpm,
                            kd1,
                            kd2,
                            kh,
                            kps,
                            b,
                            Delta,
                            L,
                            l_p,
                            beta,
                            nu_c,
                            theta_c,
                            theta_F,
                            a,
                            D_h)
    # Validate
    exp = np.array([[-3.   ,  0.   ,  0.   ,  0.   ,  0.   ,  4.   , -0.065,  0.   , 0.   ],
                    [ 1.   , -4.   ,  0.   ,  0.   ,  0.   ,  0.   ,  0.   ,  0.   , 0.   ],
                    [ 0.   ,  3.   ,  0.065,  0.   ,  0.   ,  0.   ,  0.   ,  0.   , 0.   ],
                    [ 0.   ,  0.   , -1.   , -4.   ,  0.   ,  0.   ,  0.   ,  0.   , 0.   ],
                    [ 0.   ,  0.   ,  0.   ,  4.   , -0.   ,  0.   ,  0.   ,  0.   , 0.   ],
                    [ 0.   ,  0.   , -0.065,  0.   ,  0.   , -4.   ,  0.   ,  0.   , 0.   ],
                    [ 2.   ,  0.   ,  0.   ,  0.   ,  0.   ,  0.   ,  0.065,  0.   , 0.   ],
                    [ 0.   ,  0.   ,  0.   ,  0.   ,  0.   ,  0.   , -1.   , -0.   , 0.   ],
                    [ 0.   ,  1.   ,  1.   ,  0.   ,  0.   ,  0.   ,  1.   ,  0.   , -0.   ]])
    nptest.assert_allclose(exp, got)


def test_is_transmat_const_true():
    """
    Test the is_transmat_const function with a test matrix that should return True.
    """
    # Setup
    transmat = np.array([[  -3.        ,    0.        ,    0.        ,    0.        , 0.        ,    4.        ,   36.90484031,    0.        , 0.        ],
                         [   1.        ,   -4.        ,    0.        ,    0.        , 0.        ,    0.        ,    0.        ,    0.        , 0.        ],
                         [   0.        ,    3.        , -570.40216894,    0.        , 0.        ,    0.        ,    0.        ,    0.        , 0.        ],
                         [   0.        ,    0.        ,  567.76677397,   -4.        , 0.        ,    0.        ,    0.        ,    0.        , 0.        ],
                         [   0.        ,    0.        ,    0.        ,    4.        , -0.        ,    0.        ,    0.        ,    0.        , 0.        ],
                         [   0.        ,    0.        ,    1.63539497,    0.        , 0.        ,   -4.        ,    0.        ,    0.        , 0.        ],
                         [   2.        ,    0.        ,    0.        ,    0.        , 0.        ,    0.        ,  -63.06476294,    0.        , 0.        ],
                         [   0.        ,    0.        ,    0.        ,    0.        , 0.        ,    0.        ,   25.15992264,   -0.        , 0.        ],
                         [   0.        ,    1.        ,    1.        ,    0.        , 0.        ,    0.        ,    1.        ,    0.        , -0.        ]])
    # Excercise
    got = kmc.is_transmat_const(transmat)
    # Validate
    assert got == True


def test_is_transmat_const_false():
    """
    Test the is_transmat_const function with a test matrix that should return False.
    """
    # Setup
    transmat = np.array([[-3.   ,  0.   ,  0.   ,  0.   ,  0.   ,  4.   , -0.065,  0.   , 0.   ],
                         [ 1.   , -4.   ,  0.   ,  0.   ,  0.   ,  0.   ,  0.   ,  0.   , 0.   ],
                         [ 0.   ,  3.   ,  0.065,  0.   ,  0.   ,  0.   ,  0.   ,  0.   , 0.   ],
                         [ 0.   ,  0.   , -1.   , -4.   ,  0.   ,  0.   ,  0.   ,  0.   , 0.   ],
                         [ 0.   ,  0.   ,  0.   ,  4.   , -0.   ,  0.   ,  0.   ,  0.   , 0.   ],
                         [ 0.   ,  0.   , -0.065,  0.   ,  0.   , -4.   ,  0.   ,  0.   , 0.   ],
                         [ 2.   ,  0.   ,  0.   ,  0.   ,  0.   ,  0.   ,  0.065,  0.   , 0.   ],
                         [ 0.   ,  0.   ,  0.   ,  0.   ,  0.   ,  0.   , -1.   , -0.   , 0.   ],
                         [ 0.   ,  1.   ,  1.   ,  0.   ,  0.   ,  0.   ,  1.   ,  0.   , -0.   ]])
    # Excercise
    got = kmc.is_transmat_const(transmat)
    # Validate
    assert got == False


@pytest.mark.parametrize('pos', [0, 1, 2, 3])
def test_draw_state_degenerate(pos):
    """
    Test the draw_state function when there is only one viable state to chose.
    """
    # Setup
    rates = np.zeros(4, dtype=float)
    rates[pos] = 1.
    # Excercise
    got = [kmc.draw_state(rates) for _ in range(100)]
    # Validate
    exp = np.ones(100) * pos
    nptest.assert_allclose(exp, got)


def test_draw_state_fiftyfifty():
    """
    Test the draw_state function when the choice is fifty-fifty.
    """
    # Setup
    rates = np.array([0, 1, 1, -1], dtype=float)
    num_samples = 300000
    # Excercise
    got = [kmc.draw_state(rates) for _ in range(num_samples)]
    got_states, got_counts = np.unique(got, return_counts=True)
    got_pmf = got_counts / num_samples
    # Validate
    exp_states = np.array([1, 2])
    exp_pmf = np.array([0.5, 0.5])
    nptest.assert_allclose(exp_states, got_states)
    nptest.assert_allclose(exp_pmf, got_pmf, rtol=1e-2, atol=1e-2)


@pytest.mark.parametrize('const_force, kfpp, kfpm', [(0., -1., -1.),
                                                     (-1., -1., -1.),
                                                     (-1, 2999.1290763466745, 0.019268947349062707)])
def test_kmc_myo5_trajectory_constzeroforce(const_force, kfpp, kfpm):
    """
    Test that the 'trajectory' option of the kmc driver function returns valid results.
    Tests that the returned array is of the correct shape, that the times are
    all greater than zero, are monotonically increasing, and that the motor
    displacements only happen in increments of one.
    """
    # Setup
    length = 10000

    L=35.
    l_p=310.
    D_h=5.7e7
    theta_c=np.pi / 3
    theta_F=0.
    nu_c=184.
    Delta=36.
    a=1.
    b=0.065
    kh=750.
    kd1=12.
    kd2=1.5
    kps=1e9
    beta = 0.24552442427253968
    k = 0.
    params = [kd1,
              kd2,
              kh,
              kps,
              b,
              Delta,
              L,
              l_p,
              beta,
              nu_c,
              theta_c,
              theta_F,
              a,
              D_h,
              k]
    # Excercise
    got = kmc.kmc(
            params,
            length,
            'trajectory',
            const_force,
            kfpp,
            kfpm,
            time_limit=None,
            processes=1)
    got_states = got[0]
    got_disps = got[1]
    got_dispdiff = np.diff(got_disps)
    got_times = got[2]
    got_timediff = np.diff(got_times)
    # Validate
    assert isinstance(got, np.ndarray)
    assert got.shape == (3, length)
    assert all(state in [0,1,2,3,4,5,6,7,8] for state in got_states)
    assert all([np.allclose(disp, 1.) for disp in got_dispdiff[got_dispdiff > 0]])
    assert all(got_times >= 0)
    assert all(got_timediff > 0)


@pytest.mark.parametrize('const_force, kfpp, kfpm, processes', [(0, -1, -1, 1), (0, -1, -1, 2),
                                                                (-1, -1, -1, 1), (-1, -1, -1, 2),
                                                                (-1, 2999.1290763466745, 0.019268947349062707, 1),
                                                                (-1, 2999.1290763466745, 0.019268947349062707, 2)])
def test_kmc_myo5_runstats_zeroconstforce(const_force, kfpp, kfpm, processes):
    """
    Test that the 'runstats' option of the kmc driver function returns valid results
    when operating under zero force. This is done three different ways: by setting the
    force to zero, by passing kfpp and kfpm argument equal to those calculated
    with zero force, and the last by letting the simulation calculate update
    kfp arguments each pass based on the current force, but with a zero force
    constant. Tests both single and multithreaded versions. Tests that the
    returned array is of the correct shape, that the times are all greater
    than zero, and that the averages are approximately equal to that predicted by
    Hinczewski2013. Tests both single and multiprocesses versions.
    """
    # Setup
    trials = 30000
    time_limit = 50.

    L=35.
    l_p=310.
    D_h=5.7e7
    theta_c=np.pi / 3
    theta_F=0.
    nu_c=184.
    Delta=36.
    a=1.
    b=0.065
    kh=750.
    kd1=12.
    kd2=1.5
    kps=1e9
    beta = 0.24552442427253968
    k = 0.
    params = [kd1,
              kd2,
              kh,
              kps,
              b,
              Delta,
              L,
              l_p,
              beta,
              nu_c,
              theta_c,
              theta_F,
              a,
              D_h,
              k]
    # Excercise
    got = kmc.kmc(
            params,
            trials,
            'runstats',
            const_force,
            kfpp,
            kfpm,
            time_limit=time_limit,
            processes=processes)
    got_disp = got[0]
    got_avgdisp = np.average(got_disp)
    got_time = got[1]
    got_avgtime = np.average(got_time)
    # Validate
    exp_avgdisp = 36.418 # Steps
    exp_avgtime = 3.1791 # s
    assert isinstance(got, np.ndarray)
    assert got.shape == (2, trials)
    nptest.assert_allclose(exp_avgdisp, got_avgdisp, rtol=0.05, atol=0)
    nptest.assert_allclose(exp_avgtime, got_avgtime, rtol=0.05, atol=0)


def test_emc_myo5_runstats_compforceconst():
    """
    Tests that the average run distance decreases when the motor works against a
    variable load with increased force constant.
    """
    # Setup
    trials = 30000
    time_limit = 50.
    const_force = -1.
    kfpp = -1.
    kfpm = -1.
    processes = 2

    L=35.
    l_p=310.
    D_h=5.7e7
    theta_c=np.pi / 3
    theta_F=0.
    nu_c=184.
    Delta=36.
    a=1.
    b=0.065
    kh=750.
    kd1=12.
    kd2=1.5
    kps=1e9
    beta = 0.24552442427253968
    params = [kd1,
              kd2,
              kh,
              kps,
              b,
              Delta,
              L,
              l_p,
              beta,
              nu_c,
              theta_c,
              theta_F,
              a,
              D_h]
    soft_params = params.copy() + [0.]
    strong_params = params.copy() + [4.2]
    # Excercise
    got_soft = kmc.kmc(
            soft_params,
            trials ,
            'runstats',
            const_force,
            kfpp,
            kfpm,
            time_limit=time_limit,
            processes=processes)
    got_strong = kmc.kmc(
            strong_params,
            trials,
            'runstats',
            const_force,
            kfpp,
            kfpm,
            time_limit=time_limit,
            processes=processes)

    got_soft_avgdisp = np.average(got_soft[0])
    got_strong_avgdips = np.average(got_strong[0])
    # Validate
    assert got_soft_avgdisp > got_strong_avgdips


@pytest.mark.parametrize('const_force, kfpp, kfpm, processes', [(0, -1, -1, 1), (0, -1, -1, 2),
                                                                (-1, -1, -1, 1), (-1, -1, -1, 2),
                                                                (-1, 2999.1290763466745, 0.019268947349062707, 1),
                                                                (-1, 2999.1290763466745, 0.019268947349062707, 2)])
def test_kmc_myo5_tdwell_zeroconstforce(const_force, kfpp, kfpm, processes):
    """
    Test that the 'dwell' option of the kcm driver function returns valid results.
    Tests that the returned array is of the correct shape, that the times are
    all greater than zero and that the motor and that the average dwell time is
    approximately equal to that expected for a myosin-V motor under a zero-force load
    according to Hinczewski2013. This is done three different ways: by setting the
    force to zero, by passing kfpp and kfpm argument equal to those calculated
    with zero force, and the last by letting the simulation calculate update
    kfp arguments each pass based on the current force, but with a zero force
    constant. Tests both single and multiprocessed versions.
    """
    # Setup
    trials = 30000
    time_limit = 50.

    L=35.
    l_p=310.
    D_h=5.7e7
    theta_c=np.pi / 3
    theta_F=0.
    nu_c=184.
    Delta=36.
    a=1.
    b=0.065
    kh=750.
    kd1=12.
    kd2=1.5
    kps=1e9
    beta = 0.24552442427253968
    k = 0.
    # Excercise
    params = [kd1,
              kd2,
              kh,
              kps,
              b,
              Delta,
              L,
              l_p,
              beta,
              nu_c,
              theta_c,
              theta_F,
              a,
              D_h,
              k]
    # Excercise
    got = kmc.kmc(
            params,
            trials,
            'dwell',
            const_force,
            kfpp,
            kfpm,
            time_limit=time_limit,
            processes=processes)

    got_tdwell = got[0]
    got_avgtdwell = np.average(got_tdwell)
    # Validate
    exp_avgtdwell = 0.0849 # seconds.
    assert isinstance(got, np.ndarray)
    assert got.shape == (2, trials)
    nptest.assert_allclose(exp_avgtdwell, got_avgtdwell, rtol=0.05, atol=0.)
